### ISSUE TITLE
`atscm --tasks` not working

### ISSUE THREAD

**Issue by LukasHechenberger** [atSCM/atscm-cli#22]
Currently we're running into an error when running `atscm --tasks`:

```
TypeError: Cannot read property 'description' of undefined
    at /Users/lukas/Documents/Bachmann/atscm/atscm-cli/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.2/index.js:52:17
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
```

**Comment by breussm** [comment]
We have already seen such a case, but not generally
